baseURL = 'http://example.org/'
languageCode = 'en-us'
title = "Raja's Portfolio"
theme = 'basic'

[params]
author = "Raja Shekar Bollam"
description = "This portfolio is created from 'Build Websites with Hugo' book"
